import * as assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { describe, it } from 'node:test'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const SERVER_TS = join(__dirname, '..', 'server.ts')
const CRON_TS = join(__dirname, '..', 'cron.ts')

describe('team mode hidden reviewer prompt', () => {
  it('routes specialist tasks to matching installed agents and defaults to hidden review after collaboration', () => {
    const src = readFileSync(SERVER_TS, 'utf8')
    assert.match(src, /if \(teamMode && agent\.id === 'main'\)/)
    assert.match(src, /可委派的成员（已安装 agent）/)
    assert.match(src, /listCollaboratorAgents\(teamCfg, \{ selfId: 'main', includeMain: false \}\)/)
    assert.match(src, /const model = a\.model/)
    assert.match(src, /const provider = a\.provider/)
    assert.match(src, /teamMemberCapabilityHint\(a\)/)
    assert.match(src, /\[\$\{model\}, \$\{provider\}\]/)
    assert.match(src, /领域匹配优先于泛泛并行/)
    assert.match(src, /代码\/调试\/测试\/重构\/代码库 → `coding-assistant`/)
    assert.match(src, /科研\/文献\/论文\/引用\/学术分析 → `research-assistant`/)
    assert.match(src, /文档\/PPT\/Excel\/PDF\/周报\/公文\/邮件\/办公交付 → `office-assistant`/)
    assert.match(src, /首选.*delegate_task/)
    assert.match(src, /不要优先启动 Codex 原生 `Agent`/)
    assert.match(src, /collabAgentPolicy: 'team-mode-prefer-delegate'/)
    assert.match(src, /hidden-reviewer/)
    assert.match(src, /agentId: "hidden-reviewer"/)
    assert.match(src, /不在成员列表显示/)
    assert.match(src, /完成用户任务的第一负责人/)
    assert.match(src, /端到端负责/)
    assert.match(src, /如果本轮实际调用了任何非队长成员/)
    assert.match(src, /在最终答复前默认要再调用/)
    assert.match(src, /纯机械低风险任务、用户明确要求快速\/低成本、或隐藏审查失败\/超时/)
    assert.match(src, /审查结果只是建议，不是命令/)
    assert.match(src, /已采纳的成员结论/)
    assert.match(src, /审查迭代闭环/)
    assert.match(src, /返回 PASS 或无阻塞问题/)
    assert.match(src, /返回 NEEDS_FIX 或指出具体问题/)
    assert.match(src, /不能直接结束/)
    assert.match(src, /接受并修复、委派对应领域成员修复、查询\/验证证据/)
    assert.match(src, /误报\/非问题\/范围外/)
    assert.match(src, /再次调用 `hidden-reviewer` 审查修订稿/)
    assert.match(src, /已修复项、未采纳意见及理由、关键证据/)
    assert.match(src, /迭代直到隐藏审查 PASS/)
    assert.match(src, /避免无限循环/)
    assert.match(src, /反复失败\/超时、重复没有新信息/)
    assert.match(src, /自主决定接受、拒绝、部分采纳、修订、再次审查或直接答复/)
    assert.match(src, /判断无需审查并跳过，不需要向用户解释流程/)
    assert.doesNotMatch(src, /可选审查资源，不是强制流程/)
    assert.doesNotMatch(src, /必须先形成草稿\/方案，再调用/)
  })

  it('keeps hidden reviewer out of user-facing agent management APIs', () => {
    const src = readFileSync(SERVER_TS, 'utf8')
    assert.match(src, /filterUserVisibleAgentsForManagement\(cfg\.agents\)/)
    assert.match(src, /userVisibleDefaultAgentId\(cfg\.default\)/)
    assert.match(src, /filterUserVisibleRoutesForManagement\(cfg\.routes\)/)
    assert.match(src, /isHiddenSystemAgentId\(id\).*agent not found/)
    assert.match(src, /isHiddenSystemAgentId\(agentId\).*agent not found/)
    assert.match(src, /isHiddenSystemAgentId\(body\.id\).*agent id is reserved/s)
  })

  it('rejects direct user chat/message access while leaving delegate_task as the internal path', () => {
    const src = readFileSync(SERVER_TS, 'utf8')
    assert.match(src, /if \(frame\.agentId && isHiddenSystemAgentId\(frame\.agentId\)\)/)
    assert.match(src, /if \(isHiddenSystemAgentId\(agent\.id\)\)/)
    assert.match(src, /bootAutoResume[\s\S]*isHiddenSystemAgentId\(agentId\)/)
    assert.match(src, /autoResumeFromHello[\s\S]*isHiddenSystemAgentId\(aid\)/)
    assert.match(src, /handleStop[\s\S]*explicitStopAgentId[\s\S]*isHiddenSystemAgentId\(explicitStopAgentId\)/)
    assert.match(src, /handleAgentMessage[\s\S]*isHiddenSystemAgentId\(targetAgentId\)[\s\S]*agent "[^"]+" not found/)
    assert.match(src, /handleDelegateTask[\s\S]*const targetAgent = cfg\.agents\.find\(\(a\) => a\.id === targetAgentId\)/)
  })

  it('rejects hidden reviewer from other user-controlled execution and mutation surfaces', () => {
    const src = readFileSync(SERVER_TS, 'utf8')
    const cronSrc = readFileSync(CRON_TS, 'utf8')
    // 枚举面(P2 债E 收口):skill 作用域 / webhook·task·cron 列表改走用户可见投影
    // (_getAgentsConfigUserView / filterUserVisibleByAgentField),不再各自手工过滤;
    // 守护意图不变=隐藏系统 agent 不进这些枚举面。判定面(下方 404/拒绝)仍用 predicate。
    assert.match(src, /validateSkillAgentScopeInput[\s\S]*_getAgentsConfigUserView\(\)/)
    assert.match(src, /eventBus\.on\('task\.created'[\s\S]*isHiddenSystemAgentId\(ev\.agentId\)/)
    assert.match(src, /eventBus\.on\('webhook\.received'[\s\S]*isHiddenSystemAgentId\(agentId\)/)
    assert.match(src, /filterUserVisibleByAgentField\(this\.webhookRouter\?\.list\(\) \?\? \[\]\)/)
    assert.match(src, /if \(isHiddenSystemAgentId\(wh\.agent\)\)[\s\S]*webhook not found/)
    assert.match(src, /filterUserVisibleByAgentField\(await this\._taskStore\.list\(\)\)/)
    assert.match(src, /const taskAgent = typeof agent === 'string' && agent \? agent : 'main'/)
    assert.match(src, /if \(isHiddenSystemAgentId\(taskAgent\)\) return this\.sendError\(res, 404, 'agent not found'\)/)
    assert.match(src, /if \(parsed\.agent !== undefined && isHiddenSystemAgentId\(parsed\.agent\)\)/)
    assert.match(src, /if \(isHiddenSystemAgentId\(task\.agent\)\)/)
    assert.match(src, /const cronAgent = typeof agent === 'string' && agent \? agent : 'main'/)
    assert.match(src, /if \(isHiddenSystemAgentId\(cronAgent\)\) return this\.sendError\(res, 404, 'agent not found'\)/)
    assert.match(src, /filterUserVisibleByAgentField\(await this\.cron\.listJobsWithMeta\(\)\)/)
    assert.match(cronSrc, /if \(isHiddenSystemAgentId\(job\.agent\)\)/)
  })
})
