-- order-dependency: 0290_retire_cursor_sand_for_box_claude
-- 0291_box_claude_cursor_audit.sql
-- Box Claude catalog ids are Cursor-engine rows, so the chat bridge inserts
-- them into cursor_external_usage_audit before the turn starts. The model_id
-- CHECK still lists only the old cursor-* slugs, which rejected
-- box-claude-opus-5-5 and surfaced as a generic unavailable error.

ALTER TABLE cursor_external_usage_audit
  DROP CONSTRAINT IF EXISTS cursor_external_usage_audit_model_id_check;
ALTER TABLE cursor_external_usage_audit
  ADD CONSTRAINT cursor_external_usage_audit_model_id_check CHECK (model_id IN (
      'cursor-auto',
      'cursor-grok-4.6-low',
      'cursor-grok-4.6-low-fast',
      'cursor-grok-4.6-medium',
      'cursor-grok-4.6-medium-fast',
      'cursor-grok-4.6-high',
      'cursor-grok-4.6-high-fast',
      'cursor-grok-4.6-xhigh',
      'cursor-grok-4.6-xhigh-fast',
      'cursor-grok-4.7-low',
      'cursor-grok-4.7-low-fast',
      'cursor-grok-4.7-medium',
      'cursor-grok-4.7-medium-fast',
      'cursor-grok-4.7-high',
      'cursor-grok-4.7-high-fast',
      'cursor-grok-4.7-xhigh',
      'cursor-grok-4.7-xhigh-fast',
      'cursor-composer-2.5',
      'cursor-composer-2.5-fast',
      'cursor-opus-4.8-low',
      'cursor-opus-4.8-low-fast',
      'cursor-opus-4.8-medium',
      'cursor-opus-4.8-medium-fast',
      'cursor-opus-4.8-high',
      'cursor-opus-4.8-high-fast',
      'cursor-opus-4.8-xhigh',
      'cursor-opus-4.8-xhigh-fast',
      'cursor-opus-4.8-max',
      'cursor-opus-4.8-max-fast',
      'cursor-opus-5-low',
      'cursor-opus-5-low-fast',
      'cursor-opus-5-medium',
      'cursor-opus-5-medium-fast',
      'cursor-opus-5-high',
      'cursor-opus-5-high-fast',
      'cursor-opus-5-xhigh',
      'cursor-opus-5-xhigh-fast',
      'cursor-opus-5-max',
      'cursor-opus-5-max-fast',
      'cursor-fable-5-low',
      'cursor-fable-5-medium',
      'cursor-fable-5-high',
      'cursor-fable-5-xhigh',
      'cursor-fable-5-max',
      'cursor-fable-5.1-low',
      'cursor-fable-5.1-medium',
      'cursor-fable-5.1-high',
      'cursor-fable-5.1-xhigh',
      'cursor-fable-5.1-max',
      'cursor-sonnet-5-low',
      'cursor-sonnet-5-medium',
      'cursor-sonnet-5-high',
      'cursor-sonnet-5-xhigh',
      'cursor-sonnet-5-max',
      'cursor-gemini-3.8-flash-low',
      'cursor-gemini-3.8-flash-medium',
      'cursor-gemini-3.8-flash-high',
      'cursor-gemini-3.1-pro',
      'cursor-grok-4.5-high',
      'cursor-haiku-4.5',
      'cursor-gpt-5.6-luna-low',
      'cursor-gpt-5.6-luna-low-fast',
      'cursor-gpt-5.6-luna-medium',
      'cursor-gpt-5.6-luna-medium-fast',
      'cursor-gpt-5.6-luna-high',
      'cursor-gpt-5.6-luna-high-fast',
      'cursor-gpt-5.6-luna-xhigh',
      'cursor-gpt-5.6-luna-xhigh-fast',
      'cursor-gpt-5.6-luna-max',
      'cursor-gpt-5.6-luna-max-fast',
      'box-claude-opus-5-5',
      'box-claude-sonnet-5',
      'box-claude-haiku-4-5'
  ));
