/**
 * V3 commercial container → master sink for server-authored assistant
 * messages.
 *
 * Why this exists:
 *   In v3 commercial, the per-user container runs an OpenClaude gateway
 *   with its own SQLite. But the authoritative `client_sessions` row lives
 *   in master's SQLite (the WebChat frontend PUTs there). Container's
 *   `client_sessions` is permanently empty for v3, so
 *   `appendServerAuthoredMessageDurable` always returns session_not_found
 *   and dead-letters into the local msg-outbox.jsonl. On startup,
 *   `replayMsgOutbox` permanently drops session_not_found entries — the
 *   row is never going to materialise locally. Result: every turn's
 *   authoritative assistant text was lost, and mobile clients that missed
 *   the streaming tail had nothing to recover via REST force-sync.
 *
 *   This module is the container-side counterpart of master's
 *   `packages/commercial/src/http/internalServerAuthored.ts`. We POST to
 *   master via the same internal listener that already terminates
 *   anthropicProxy traffic (self-host plain 18791 / remote-host mTLS
 *   18443) — the route splitter on master mounts our handler on
 *   `/internal/v3/server-authored-message`. Reusing the listener means
 *   no new ports, no new firewall rules, and the same container identity
 *   bearer (`oc-v3.<containerId>.<secret>`) is honoured by the same
 *   `verifyContainerIdentity` machinery on master.
 *
 * Module split:
 *   - `attemptSendLossless(...)` — current v2 multipart+hash protocol. Every
 *     generated byte is staged locally before upload and retained until ACK.
 *   - `attemptSend(...)` — v2 sender for both live turns and old on-disk
 *     entries. Pre-agentId v1 entries are upgraded with a reserved identity;
 *     they never re-enter the lossy single-body endpoint.
 *   - `getV3MasterSinkOrNull()` — reads env, returns a closure-bound
 *     sink, or null if env missing (personal version, dev sandbox, etc.).
 *   - `persistOrQueue(...)` — high-level helper sessionManager calls:
 *     awaits one attempt; on transient/session_missing/network/auth
 *     failures keeps the already-fsynced durable retry entry. Only an
 *     explicit 410 session-deletion acknowledgement permits deletion.
 *
 * Trust boundary:
 *   - Bearer goes in `Authorization: Bearer oc-v3.<id>.<secret>`. We
 *     never log the bearer or echo it into error messages.
 *   - We never send `userId` / `peerId` / `id` over the wire — master
 *     derives those from the verified identity + (sessionId, turnIndex)
 *     to keep tenant isolation tight.
 *   - Body fields are validated client-side ONLY for size sanity (so we
 *     don't enqueue obviously bogus payloads); master's Zod schema is
 *     authoritative.
 *
 * Current v2 failure semantics:
 *   - 200 ok / 200 idempotent → success, drop entry.
 *   - 410 SESSION_DELETED → owner deletion ACK; remove the entry.
 *   - every other HTTP/network/auth/contract failure → retain and retry;
 *     contract-conflicting files may be quarantined but their bytes remain.
 */

import { request as undiciRequest } from 'undici'
import { createHash } from 'node:crypto'
import {
  LOSSLESS_TURN_TAPE_LEGACY_AGENT_ID,
  LOSSLESS_TURN_TAPE_PART_BYTES,
  LOSSLESS_TURN_TAPE_VERSION,
  type DurableAgentGroup,
  type DurableCodexBilling,
  type LosslessTurnTapeFinalizeRequest,
  type LosslessTurnTapePartRequest,
  type TurnWaiveReason,
} from '@openclaude/protocol'

import { createLogger } from './logger.js'
import type { TurnToolEntry } from './ccbMessageParser.js'
import type { DurableRuntimeEvent } from './engine/engineEvents.js'
import type { V3MasterRetryQueue, V3MasterRetryEntry } from './v3MasterRetryQueue.js'

const log = createLogger({ module: 'v3MasterSink' })

/** Master's path for server-authored messages. Must match the master
 *  side's `SERVER_AUTHORED_PATH` constant. Don't import from commercial —
 *  gateway is shipped INTO the container image and must not depend on
 *  master-only packages at compile time. Path is part of the wire
 *  contract; master + gateway change it together. */
export const SERVER_AUTHORED_PATH = '/internal/v3/server-authored-message'

/** Bounds only an HTTP error/ACK body held for diagnostics. It never touches
 * generated turn content,which is uploaded as content-addressed parts. */
const MAX_DIAGNOSTIC_RESPONSE_BYTES = 256 * 1024

/** HTTP timeout per staged part. Finalize is content-sized work and has no
 * product-level deadline: the fsynced queue remains the durable owner until
 * the master returns an ACK. */
const ATTEMPT_TIMEOUT_MS = 10_000

/**
 * Wire-shape payload. Mirrors what attemptSend serializes to the master.
 *
 * `agentId` is the disambiguator that joins (peerId, agentId, turnIndex)
 * into a globally unique messageId: a single chat (peerId) can rotate
 * across multiple AgentSessions (e.g. user switches model mid-chat,
 * codex → main), each tracking its own `session.turns` counter starting
 * at 0. Without `agentId` the resulting `srv-${peerId}-t1` collides and
 * the client merges two distinct answers into one row (root cause of the
 * 2026-05-13 "switched to deepseek, only thinking visible" bug). Master
 * folds it into the persisted message id (`srv-${peerId}-${agentId}-t${n}`)
 * so refresh-recovery from SQLite recovers the disambiguated row too.
 *
 * Wire optional vs live required: the on-disk retry queue may carry
 * entries written by a pre-Fix-A gateway image (no `agentId` field) —
 * the drainer must be able to deserialize them. So this wire shape
 * marks `agentId?: string`. Live callers in sessionManager use the
 * stricter {@link V3MasterSinkPayload} that requires `agentId`.
 */
export interface V3MasterSinkWirePayload {
  /** Agent that produced this turn. Optional on the wire ONLY to allow
   *  the retry queue to deserialize legacy on-disk entries. New live
   *  callers always set this; absence implies "old queue entry, fall
   *  back to peerId-only messageId on the master side". */
  agentId?: string
  sessionId: string
  turnIndex: number
  /** Browser-authored persisted user-row id for this webchat turn. Optional
   * for legacy retry-queue entries and non-webchat producers. */
  clientMessageId?: string
  /** RFC-v5-durable-turn-dispatch §2.4/§3 — durable dispatch identity. Present
   * only on webchat-DM turns admitted through the durable inbox. Rides the
   * canonical tape payload (enters the tape hash) so the master ACK can drive
   * the container inbox row to terminal keyed by (dispatchId, attemptNo). */
  dispatchId?: string
  attemptNo?: number
  status: 'completed' | 'interrupted' | 'crashed'
  /** Stable logical turn identity used by lossless persistence and exact billing. */
  turnKey?: string
  /** Platform-owned reason for waiving this exact logical turn. It travels
   * with every fsynced tape envelope so retries cannot lose the billing fence. */
  waiveReason?: TurnWaiveReason
  /** This tape is an immutable post-terminal continuation of an already
   * finalized paid turn (currently CCB background Bash tail events). It is
   * content-only and must never consume or redirect billing patches. */
  continuationOfTurnKey?: string
  /** Delegate usage is attributed to this leader turn when present. */
  parentTurnKey?: string
  /** Assistant text — the user-visible content. Always written if non-empty.
   *  Empty string is allowed when this is a thinking-only turn (Sonnet 4.6
   *  adaptive thinking that ran out of tokens before producing text). */
  text: string
  /** Optional full reasoning/thinking text accumulated by ccbMessageParser.
   *  Current v2 persists it without semantic truncation. Master materializes a
   *  separate `_source: 'server'` message with `role: 'thinking'` and
   *  ts = assistantTs - 1 so it sorts immediately before the assistant
   *  message of the same turn. */
  thinkingText?: string
  /** Optional client-supplied wall-clock ms; master uses this for the
   *  message ts so all clients see the same timestamp regardless of
   *  retry timing. Defaults to Date.now() at master if omitted. */
  createdAt?: number
  /** Plan §4.4 改动 7 — required when text is non-empty. Joins this
   *  assistant message with the eventual `appendCostCredits` patch via
   *  master's `server_authored_request_map` table. Caller propagates this
   *  from the upstream proxy `x-openclaude-request-id` header captured at
   *  stream begin, so master and gateway agree on a single key. */
  requestId?: string
  /** CCB agent session id(= runner.sessionId / ccb getSessionId）。透传给 master,
   *  使 ccb 助手落库时按 session 精确排空 pending costCredits(anthropicProxy 异步算费
   *  park 时以 LLM metadata.session_id 为 key,与此一致)。缺省 → master 退回 by-user。 */
  agentSessionId?: string
  /** Platform goal captured before this turn started. Both fields must be
   * present together; master validates ownership against sessionId. */
  goalId?: string
  goalStateRevision?: number
  /** Plan §4.4 改动 7 — token usage gathered by the gateway-side stream
   *  finalizer at `message_stop`. Persisted into `messages[i].usage`;
   *  costCredits joins later via `appendCostCredits`. Snake-case JSON
   *  field names (matching master schema in `internalServerAuthored.ts`)
   *  are camelCased here for TS hygiene. */
  usage?: {
    inputTokens?: number
    outputTokens?: number
    cacheReadTokens?: number
    cacheCreationTokens?: number
    model?: string
    turn?: number
    /** Master-owned per-turn canonical traceId (generated at inbound.message
     *  entry, stamped onto the outbound.message frame). Folded into
     *  `messages[i].usage.traceId` so the web UI can surface a copyable
     *  "请求ID" that ops greps verbatim against master turn logs — and so it
     *  survives refresh via the same server-authoritative usage sync channel
     *  as inputTokens/costCredits. Nested under usage (not a sibling) because
     *  usage is already the sync overlay key carrying turn metadata (model/
     *  turn), so traceId rides existing rails with no new overlay-key wiring. */
    traceId?: string
  }
  /** Plan §4.4 改动 7 — turn was truncated (max_tokens / stop_reason
   *  diverged from `end_turn`). Renders the red "已截断" pill on the
   *  assistant message after a refresh. */
  truncated?: boolean
  /** Plan §4.4 改动 7 — short error code for refresh-stable error pill
   *  (e.g. 'overloaded_error'). Joins `errorDetail` for the long form. */
  errorCode?: string
  errorDetail?: string
  /** Top-level tool calls completed in this turn. Canonical input/output fields
   *  are complete; only the explicitly named UI preview is short.
   *  Master persists each as a separate `_source: 'server'` message with
   *  `role: 'tool'` between thinking and assistant of the same turn — that
   *  durable copy is what survives a refresh, replacing the ephemeral
   *  client-authored tool rows whose details are stripped on persist.
   *  Current v2 never drops this array. `attemptSend` policies are legacy-v1.
   *
   *  Fix B (2026-05-25): each `TurnToolEntry.arrivedAt` is the tool CARD
   *  APPEARANCE time (parser-stamped at first tool_use observation, NEW
   *  field). Master priority chain `arrivedAt ?? (baseTs - toolsCount + i)`
   *  prefers it for the persisted row ts so parallel-tool refresh order
   *  matches the live emit order. The legacy `ts` field retains the
   *  tool_result completion semantic and is ignored by master (preserves
   *  pre-Fix-B behavior for old gateways). */
  tools?: TurnToolEntry[]
  /** Fix B (2026-05-25) — per-text-segment payload. When present, master
   *  writes ONE assistant row per segment (`srv-...-tN-s${idx}`) with the
   *  segment's own ts so ts-sort interleaves correctly with tool rows.
   *  When absent (old gateway, legacy callers), master falls back to the
   *  single-row `text` field above.
   *  Plan: docs/wip/fixb-per-segment-row-id-PLAN.md §3.5.1. */
  assistantSegments?: Array<{ index: number; text: string; ts: number; eventOrdinal?: number }>
  /** Fix B (2026-05-25) — same per-segment treatment for thinking rows
   *  (`srv-...-tN-thinking-s${idx}`). */
  thinkingSegments?: Array<{ index: number; text: string; ts: number; eventOrdinal?: number }>
  /** P2 债A — completed delegations (team cards) for this leader turn. Buffered
   *  on the parent session as delegates finish and drained with the turn-end
   *  persist. Master writes each as a server-authored `role: 'agent-group'`
   *  row so team structure survives cross-device / cleared cache / a missed
   *  client PUT (the durability gap: server-authored channel previously only
   *  carried assistant/thinking/tool). Current v2 keeps every group and its
   *  full descendant transcript; any `attemptSend` cascade is legacy-v1. */
  agentGroups?: DurableAgentGroup[]
  /** Main-agent structured response blocks that are not represented by the
   * text/thinking/tool/group aggregates (currently plan + goal). Every update
   * is retained so refresh recovery does not depend on a browser PUT. */
  structuredBlocks?: Array<Record<string, unknown>>
  /** Exact opaque CCB/Codex protocol stream, globally ordered and uncapped. */
  runtimeEvents?: DurableRuntimeEvent[]
  /** Final engine-reported usage, durably co-located with the paid turn. */
  engineBilling?: DurableCodexBilling
}

/**
 * Live caller payload — required by sessionManager.persistServerAuthoredTurn
 * and the V3MasterSink interface. Tightens {@link V3MasterSinkWirePayload}
 * by making `agentId` non-optional, matching the in-process invariant that
 * any live turn-end has a known agentId (AgentSession.agentId is set at
 * getOrCreate time). The wire variant exists ONLY so the retry queue can
 * deserialize pre-Fix-A disk entries.
 */
export interface V3MasterSinkPayload extends V3MasterSinkWirePayload {
  agentId: string
}

export type V3SinkErrorClass = 'transient' | 'session_missing' | 'fatal'

/** Base class so callers can `instanceof V3SinkError` to gate fallback. */
export class V3SinkError extends Error {
  constructor(
    message: string,
    public readonly errorClass: V3SinkErrorClass,
    public readonly httpStatus?: number,
  ) {
    super(message)
    this.name = 'V3SinkError'
  }
}

export interface V3MasterSinkConfig {
  baseUrl: string
  bearer: string
}

/** Read env-driven config. Returns null when either env is missing —
 *  personal version + dev sandbox don't set them, and we want to
 *  no-op silently in that case (sessionManager falls back to the
 *  legacy local durable path). */
export function readV3MasterSinkConfig(env: NodeJS.ProcessEnv = process.env): V3MasterSinkConfig | null {
  const baseUrl = env.OPENCLAUDE_V3_MASTER_BASE_URL
  const bearer = env.OPENCLAUDE_V3_CONTAINER_TOKEN
  if (!baseUrl || !bearer) return null
  // Strip trailing slash so URL composition is unambiguous.
  return { baseUrl: baseUrl.replace(/\/+$/, ''), bearer }
}

export interface AttemptSendDeps {
  config: V3MasterSinkConfig
  /** Override only for tests — real callers use undici. */
  fetcher?: typeof undiciRequest
  /** Override only for tests — real callers use Date.now. */
  now?: () => number
  /** Override only for tests — real callers use ATTEMPT_TIMEOUT_MS. */
  timeoutMs?: number
}

function sha256(value: Buffer | string): string {
  return createHash('sha256').update(value).digest('hex')
}

/** JSON canonicalization: object keys sorted recursively, array order retained. */
export function serializeLosslessTurnPayload(value: unknown): Buffer {
  const json = JSON.stringify(value, (_key, current) => {
    if (!current || typeof current !== 'object' || Array.isArray(current)) return current
    const sorted: Record<string, unknown> = {}
    for (const key of Object.keys(current as Record<string, unknown>).sort()) {
      sorted[key] = (current as Record<string, unknown>)[key]
    }
    return sorted
  })
  if (json === undefined) throw new V3SinkError('turn payload is not JSON serializable', 'transient')
  return Buffer.from(json, 'utf8')
}

export function deriveLosslessTurnKey(payload: V3MasterSinkWirePayload): string {
  if (payload.turnKey && /^[0-9a-f]{64}$/.test(payload.turnKey)) return payload.turnKey
  return sha256(`oc-turn-v2\0${payload.sessionId}\0${payload.agentId ?? 'legacy'}\0${payload.turnIndex}`)
}

export function buildLosslessTurnTapeRequests(
  payload: V3MasterSinkWirePayload & { agentId: string },
  now: () => number = Date.now,
): { finalize: LosslessTurnTapeFinalizeRequest; canonical: Buffer } {
  const createdAt = payload.createdAt ?? now()
  const turnKey = deriveLosslessTurnKey(payload)
  const canonical = serializeLosslessTurnPayload({ ...payload, createdAt, turnKey })
  const tapeSha256 = sha256(canonical)
  const tapeId = sha256(`oc-tape-v2\0${turnKey}`)
  const partCount = Math.ceil(canonical.length / LOSSLESS_TURN_TAPE_PART_BYTES)
  const base = {
    protocolVersion: LOSSLESS_TURN_TAPE_VERSION,
    sessionId: payload.sessionId,
    agentId: payload.agentId,
    turnIndex: payload.turnIndex,
    status: payload.status,
    turnKey,
    tapeId,
    tapeSha256,
    totalBytes: canonical.length,
    partCount,
    createdAt,
    ...(payload.waiveReason ? { waiveReason: payload.waiveReason } : {}),
    // RFC §2.4:dispatch 身份随信封上行(sink 首片 → master 落 tape header → finalize 同事务
    // 收敛 turn_dispatches)。2026-07-18 实证:此处漏传 → 全量 tape 无身份 → dispatch 恒停
    // accepted、零 terminal。canonical/hash 不受影响(payload 本体本就含 dispatchId,此处
    // 只是信封元数据补齐)。
    ...(typeof payload.dispatchId === 'string' && typeof payload.attemptNo === 'number'
      ? { dispatchId: payload.dispatchId, attemptNo: payload.attemptNo }
      : {}),
  } as const
  return { finalize: { ...base, action: 'finalize' }, canonical }
}

/** Yield one base64 envelope at a time. Production never retains an array of
 * all encoded parts (which previously added ~4/3 of the whole turn again). */
export function* iterateLosslessTurnTapeParts(
  tape: ReturnType<typeof buildLosslessTurnTapeRequests>,
): Generator<LosslessTurnTapePartRequest> {
  const { action: _action, ...base } = tape.finalize
  for (let partIndex = 0; partIndex < tape.finalize.partCount; partIndex++) {
    const bytes = tape.canonical.subarray(
      partIndex * LOSSLESS_TURN_TAPE_PART_BYTES,
      Math.min(tape.canonical.length, (partIndex + 1) * LOSSLESS_TURN_TAPE_PART_BYTES),
    )
    yield {
      ...base,
      action: 'part',
      partIndex,
      partSha256: sha256(bytes),
      data: bytes.toString('base64'),
    }
  }
}

async function postLosslessTurnTapeEnvelope(
  envelope: LosslessTurnTapePartRequest | LosslessTurnTapeFinalizeRequest,
  deps: AttemptSendDeps,
): Promise<void> {
  const fetcher = deps.fetcher ?? undiciRequest
  const isFinalize = envelope.action === 'finalize'
  const controller = isFinalize ? null : new AbortController()
  const timer = controller === null
    ? null
    : setTimeout(() => controller.abort(), deps.timeoutMs ?? ATTEMPT_TIMEOUT_MS)
  let res: Awaited<ReturnType<typeof undiciRequest>>
  try {
    res = await fetcher(`${deps.config.baseUrl}${SERVER_AUTHORED_PATH}`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json; charset=utf-8',
        authorization: `Bearer ${deps.config.bearer}`,
      },
      body: JSON.stringify(envelope),
      ...(controller === null
        ? {
            // A large lossless tape can legitimately take minutes to verify
            // and materialize. Undici's default headers timeout would turn
            // that valid work into overlapping retries. Connection failures
            // still reject normally; there is simply no content-size timer.
            headersTimeout: 0,
            bodyTimeout: 0,
          }
        : { signal: controller.signal }),
    })
  } catch (err) {
    if (timer !== null) clearTimeout(timer)
    throw new V3SinkError(`network error: ${err instanceof Error ? err.message : String(err)}`, 'transient')
  }
  if (timer !== null) clearTimeout(timer)
  let bodyText = ''
  try {
    bodyText = await readBoundedBody(res.body, MAX_DIAGNOSTIC_RESPONSE_BYTES)
  } catch {
    // Status remains authoritative when an error response body cannot be read.
  }
  const status = res.statusCode
  if (status >= 200 && status < 300) return
  if (status === 404) {
    throw new V3SinkError(`session_not_found: ${truncateForLog(bodyText)}`, 'session_missing', status)
  }
  if (status === 410) {
    throw new V3SinkError(`session_deleted: ${truncateForLog(bodyText)}`, 'fatal', status)
  }
  // Contract conflicts, auth errors, body errors and server errors are all
  // operationally repairable. Keep retrying the immutable local tape; 410 is
  // the sole deletion acknowledgement allowed to discard it.
  throw new V3SinkError(`master ${status}: ${truncateForLog(bodyText)}`, 'transient', status)
}

export async function attemptSendLossless(
  payload: V3MasterSinkWirePayload & { agentId: string },
  deps: AttemptSendDeps,
): Promise<void> {
  const tape = buildLosslessTurnTapeRequests(payload, deps.now)
  for (const part of iterateLosslessTurnTapeParts(tape)) {
    await postLosslessTurnTapeEnvelope(part, deps)
  }
  await postLosslessTurnTapeEnvelope(tape.finalize, deps)
}

/**
 * Upload one turn through the v2 multipart protocol.
 *
 * Old retry entries can lack `agentId`. They are upgraded in-memory with a
 * reserved identity rather than replayed through the historical single-body
 * endpoint,whose byte/count guards discarded thinking,tools,and delegation
 * details. The master maps this reserved identity back to the original v1
 * record-id namespace,so an ACK-lost v1 commit is replaced idempotently.
 */
export async function attemptSend(
  payload: V3MasterSinkWirePayload,
  deps: AttemptSendDeps,
): Promise<void> {
  const upgraded: V3MasterSinkWirePayload & { agentId: string } = payload.agentId
    ? payload as V3MasterSinkWirePayload & { agentId: string }
    : { ...payload, agentId: LOSSLESS_TURN_TAPE_LEGACY_AGENT_ID }
  await attemptSendLossless(upgraded, deps)
}

async function readBoundedBody(
  body: { [Symbol.asyncIterator](): AsyncIterableIterator<Buffer | Uint8Array | string> },
  max: number,
): Promise<string> {
  let total = 0
  const chunks: Buffer[] = []
  for await (const chunk of body) {
    const b = chunk instanceof Buffer
      ? chunk
      : typeof chunk === 'string'
        ? Buffer.from(chunk, 'utf8')
        : Buffer.from(chunk)
    total += b.length
    if (total > max) break
    chunks.push(b)
  }
  return Buffer.concat(chunks, Math.min(total, max)).toString('utf8')
}

function truncateForLog(s: string): string {
  if (s.length <= 200) return s
  return s.slice(0, 200) + '…'
}

// ─── high-level orchestration ───────────────────────────────────────────

export interface V3MasterSink {
  /** Stage durably, then try once. Any non-410 failure remains retained for
   *  retry; 410 is the sole deletion ACK. Returns the outcome so callers can metric.
   *  Live caller path — payload must include `agentId`. */
  persistOrQueue(payload: V3MasterSinkPayload): Promise<PersistOutcome>
  /** Single-attempt for the drainer to call directly without going
   *  through enqueue. Accepts the wire shape (agentId optional) so the
   *  retry queue can drain pre-Fix-A on-disk entries that were written
   *  before the agentId field existed. Missing legacy agent IDs are upgraded
   *  to the reserved v2 identity that preserves the historical message IDs. */
  attemptOnce(payload: V3MasterSinkWirePayload): Promise<void>
}

export type PersistOutcome =
  | { ok: true }
  | { ok: false; queued: true; errorClass: 'transient' | 'session_missing' }
  | { ok: false; queued: false; droppedReason: string }

/** RFC-v5-durable-turn-dispatch §3/§B6 — durable inbox lifecycle hooks. Fired only
 * for payloads carrying a `dispatchId` (webchat-DM durable turns); ordinary
 * turns / legacy entries no-op.
 *
 * B6 — **awaited durable migration (best-effort removed)**: each hook is awaited so the
 * inbox state transition is confirmed before persistOrQueue proceeds.
 *
 * M-R1-1 ① — **onAck gates the durable entry deletion**: `onAck` returns whether the inbox
 * terminal CAS is confirmed landed (`true`) or not (`false`). persistOrQueue must call it
 * **before** `ackDurable` and only delete the staged entry when it returns `true`; a `false`
 * (terminal write failed) keeps the entry so the drainer retries the terminal migration
 * (idempotent: master finalize idempotent + inbox CAS idempotent). This closes the hole where
 * the old order (ackDurable → onAck) deleted the entry, then swallowed a terminal-write failure,
 * leaving the inbox permanently `sink_staged` (periodic recovery previously no-op'd on it).
 *
 * `onStaged`/`onStageFailed` remain best-effort-migration (own their error handling + rely on
 * periodic recovery); only `onAck` carries the confirm/keep signal because only it gates deletion. */
export interface V3DispatchInboxHooks {
  /** After the tape is fsynced to the retry queue (running → sink_staged). */
  onStaged?: (dispatchId: string, attemptNo: number) => void | Promise<void>
  /** After master ACK — drives the inbox row to terminal. Returns `true` when the terminal
   *  state is confirmed reached (or already terminal — idempotent); `false` when the terminal
   *  write failed and the durable entry must be kept for a drainer retry. */
  onAck?: (
    dispatchId: string,
    attemptNo: number,
    status: 'completed' | 'interrupted' | 'crashed',
  ) => boolean | Promise<boolean>
  /** stageDurable itself failed (I/O) — never fsynced (→ sink_stage_failed). */
  onStageFailed?: (dispatchId: string, attemptNo: number) => void | Promise<void>
}

export interface MakeV3MasterSinkDeps {
  config: V3MasterSinkConfig
  retryQueue: V3MasterRetryQueue
  /** Override only for tests. */
  attemptSendImpl?: typeof attemptSend
  now?: () => number
  /** RFC-v5-durable-turn-dispatch §3 inbox hooks (best-effort). */
  inboxHooks?: V3DispatchInboxHooks
}

/** B6 — await the inbox migration hook; a thrown/rejected hook is logged but never breaks the
 *  lossless persistence outcome. Awaiting (vs the old fire-and-forget `void`) is what makes the
 *  state transition confirmed-synchronous before persistOrQueue moves on. Used by the best-effort
 *  hooks (onStaged / onStageFailed) that do not gate the durable entry deletion. */
async function fireInboxHook(fn: (() => void | Promise<void>) | undefined): Promise<void> {
  if (!fn) return
  try {
    await fn()
  } catch (err) {
    log.warn('v3 sink: dispatch inbox hook threw', undefined, err)
  }
}

/** M-R1-1 ① — fire the onAck hook and report whether the inbox terminal CAS is confirmed.
 *  No hook → `true` (nothing to converge, safe to ack). A thrown/rejected hook is treated as
 *  `false` (not confirmed) so the durable entry is kept for a drainer retry rather than deleted
 *  on an unconfirmed terminal. */
async function fireInboxAckHook(
  fn: V3DispatchInboxHooks['onAck'],
  dispatchId: string,
  attemptNo: number,
  status: 'completed' | 'interrupted' | 'crashed',
): Promise<boolean> {
  if (!fn) return true
  try {
    return await fn(dispatchId, attemptNo, status)
  } catch (err) {
    log.warn('v3 sink: onAck inbox hook threw; retaining entry for retry', undefined, err)
    return false
  }
}

export function makeV3MasterSink(deps: MakeV3MasterSinkDeps): V3MasterSink {
  const now = deps.now ?? (() => Date.now())
  const hooks = deps.inboxHooks

  const attemptOnce = (payload: V3MasterSinkWirePayload): Promise<void> => {
    if (deps.attemptSendImpl) return deps.attemptSendImpl(payload, { config: deps.config })
    return attemptSend(payload, { config: deps.config })
  }

  const persistOrQueue = async (payload: V3MasterSinkPayload): Promise<PersistOutcome> => {
    // Paid output is durable before the first network attempt. A process or
    // host crash between model completion and master ACK therefore leaves an
    // immutable replayable entry instead of an acknowledged-looking hole.
    const firstSeenAt = now()
    const entry: V3MasterRetryEntry = {
      schemaVersion: 1,
      payload: { ...payload, createdAt: payload.createdAt ?? firstSeenAt },
      firstSeenAt,
      attempts: 0,
    }
    const dispatchId = payload.dispatchId
    const attemptNo = payload.attemptNo
    const hasDispatch = typeof dispatchId === 'string' && typeof attemptNo === 'number'
    let receipt: string
    try {
      receipt = await deps.retryQueue.stageDurable(entry)
    } catch (err) {
      // stageDurable 抛 = 从未 fsync(ENOSPC 等)→ 行仍 running。**await** sink_stage_failed
      // 迁移(B6:同步确认,不再 fire-and-forget),再 rethrow(唯一真失败)。写入自身若失败,
      // hook 内 error log + 行留 running 由周期 recovery 兜底(不静默停在 running)。
      if (hasDispatch)
        await fireInboxHook(() => hooks?.onStageFailed?.(dispatchId as string, attemptNo as number))
      throw err
    }
    // tape 已 durable → running 转 sink_staged(master ACK 前的可恢复态)。await 确认迁移。
    if (hasDispatch)
      await fireInboxHook(() => hooks?.onStaged?.(dispatchId as string, attemptNo as number))
    try {
      await attemptOnce(entry.payload)
      // M-R1-1 ①:顺序反转 —— master 同步 ACK 成功后,**先**确认 inbox terminal CAS 落库,
      // **再** ackDurable 删 durable entry。terminal 写失败(onAck 返回 false)→ 不删 entry:
      // tape 已在 master(finalize 幂等),但去重态未收敛 → 保留 entry 让 drainer 重试终态迁移
      // (inbox CAS 幂等),避免"entry 已删、行永停 sink_staged"的静默停摆。
      if (hasDispatch) {
        const confirmed = await fireInboxAckHook(
          hooks?.onAck,
          dispatchId as string,
          attemptNo as number,
          payload.status,
        )
        if (!confirmed) {
          deps.retryQueue.kick()
          log.info('v3 master sink: inbox terminal CAS unconfirmed, retaining entry for retry', {
            sessionId: payload.sessionId,
            turnIndex: payload.turnIndex,
          })
          return { ok: false, queued: true, errorClass: 'transient' }
        }
      }
      await deps.retryQueue.ackDurable(receipt)
      return { ok: true }
    } catch (err) {
      if (err instanceof V3SinkError) {
        if (err.errorClass === 'fatal' && err.httpStatus === 410) {
          // The owner deleted the session. This is the sole remote ACK that
          // permits discarding an otherwise valid paid-turn tape.
          await deps.retryQueue.ackDurable(receipt)
          return { ok: false, queued: false, droppedReason: err.message }
        }
        if (
          err.errorClass === 'transient' ||
          err.errorClass === 'session_missing' ||
          err.errorClass === 'fatal'
        ) {
          // Keep the already-staged immutable entry. The drainer retries
          // operational errors and quarantines non-410 contract conflicts;
          // neither path deletes user content.
          deps.retryQueue.kick()
          const errorClass = err.errorClass === 'session_missing'
            ? 'session_missing'
            : 'transient'
          log.info('v3 master sink: enqueued for retry', {
            sessionId: payload.sessionId,
            turnIndex: payload.turnIndex,
            errorClass,
            httpStatus: err.httpStatus,
          })
          return { ok: false, queued: true, errorClass }
        }
      }
      // Unknown throw — defensively classify as transient so we don't
      // drop user data on a bug we didn't anticipate.
      log.error(
        'v3 master sink: unexpected throw, treating as transient',
        { sessionId: payload.sessionId, turnIndex: payload.turnIndex },
        err,
      )
      deps.retryQueue.kick()
      return { ok: false, queued: true, errorClass: 'transient' }
    }
  }

  return { persistOrQueue, attemptOnce }
}

// ─── module-level singleton (set at startup, read at turn-end) ──────────

let singleton: V3MasterSink | null = null

/** Wire at startup from server.ts. Pass null to disable explicitly
 *  (tests, dev). */
export function setV3MasterSinkSingleton(sink: V3MasterSink | null): void {
  singleton = sink
}

/** Returns the current sink, or null if not configured. sessionManager
 *  uses this gate to choose between v3-master-sink and the legacy
 *  durable local-SQLite path. */
export function getV3MasterSinkOrNull(): V3MasterSink | null {
  return singleton
}
