import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = process.cwd()
const relay = readFileSync(resolve(root, 'packages/gateway/src/engine/cursorSandRelay.ts'), 'utf8')
const inferenceProto = readFileSync(resolve(root, 'packages/gateway/src/engine/cursorSandInference.proto'), 'utf8')
const adapter = readFileSync(resolve(root, 'packages/gateway/src/engine/cursorSandAdapter.ts'), 'utf8')
const routing = readFileSync(resolve(root, 'packages/gateway/src/engine/cursorRoutingAdapter.ts'), 'utf8')
const selection = readFileSync(resolve(root, 'packages/gateway/src/engine/cursorCredentialSelection.ts'), 'utf8')
const registry = readFileSync(resolve(root, 'packages/gateway/src/engine/cursorAdapter.ts'), 'utf8')
const wrapper = readFileSync(resolve(root, 'packages/commercial/agent-sandbox/platform-runtime/bin/oc-cursor.sh'), 'utf8')
const tests = readFileSync(resolve(root, 'packages/gateway/src/__tests__/cursorSandRelay.test.ts'), 'utf8')
const resumeTests = readFileSync(resolve(root, 'packages/gateway/src/__tests__/sessionManagerResumeMap.test.ts'), 'utf8')
const wrapperTests = readFileSync(resolve(root, 'packages/commercial/src/__tests__/cursorCliWrapper.test.ts'), 'utf8')
const materializer = readFileSync(resolve(root, 'packages/commercial/src/account-pool/cursorMaterializer.ts'), 'utf8')
const quota = readFileSync(resolve(root, 'packages/commercial/src/account-pool/cursorQuota.ts'), 'utf8')
const bridge = readFileSync(resolve(root, 'packages/commercial/src/ws/userChatBridge.ts'), 'utf8')
const frames = readFileSync(resolve(root, 'packages/protocol/src/frames.ts'), 'utf8')
const commercialDeploy = readFileSync(resolve(root, 'scripts/deploy-v5.sh'), 'utf8')
const selfhostRelease = readFileSync(resolve(root, 'scripts/v5-selfhost-master-release-lib.sh'), 'utf8')

assert.match(relay, /\/aiserver\.v1\.InferenceService\/Stream/)
assert.match(relay, /'x-cursor-client-type': 'sand'/)
assert.doesNotMatch(relay, /agent\.v1\.AgentService\/Run/)
assert.doesNotMatch(relay, /startsWith\('claude-fable-5'\)/)
assert.match(inferenceProto, /Struct parameters = 3;/)
assert.doesNotMatch(inferenceProto, /parameters_json_schema/)
assert.match(relay, /jsonSchema: protoValue\(schema\)/)
assert.match(relay, /rawToolCallArgs: JSON\.stringify/)
assert.match(relay, /toolContent:/)
assert.match(relay, /mergeToolPart\(state\.tools, part\)/)
assert.match(adapter, /await this\.prepareRelay\(generation\)/)
assert.match(adapter, /this\.emit\('external_billing'/)
assert.match(adapter, /cursorSlotResults:/)
assert.match(adapter, /supportsNativeCompact: false/)
assert.match(registry, /CURSOR_SAND_RESUME_PREFIX = 'sand-ccb:'/)
assert.match(routing, /resumeForVariant\(this\.opts\.resumeSessionId, variant\)/)
assert.match(routing, /variant === 'sand'/)
assert.match(routing, /new CursorSandAdapter\(innerOpts\)/)
assert.match(routing, /new CursorAdapter\(innerOpts\)/)
assert.match(routing, /CURSOR_SAND_RESUME_PREFIX/)
assert.match(routing, /cursorSandResumeInnerId/)
assert.match(routing, /await this\.ensureVariant\(generation\)/)
assert.match(routing, /opts\.cursorCredentialSelection \?\? selector\(/)
assert.match(routing, /cursorCredentialSelection: this\.credentialSelection/)
assert.doesNotMatch(routing, /compactForHandoff/)
assert.match(selection, /OPENCLAUDE_CURSOR_SELECT_ONLY/)
assert.match(selection, /OPENCLAUDE_CURSOR_SELECTED_KEY/)
assert.match(selection, /OPENCLAUDE_CURSOR_POOL_GENERATION/)
assert.match(wrapper, /oc-cursor: selected_slot/)
assert.doesNotMatch(wrapper, /set -- -H "x-cursor-client-type: sand"/)
assert.match(registry, /new CursorRoutingAdapter\(opts\)/)
assert.match(registry, /env\.OPENCLAUDE_CURSOR_SELECTED_KEY/)
assert.match(tests, /tool recovery accepts XML and bounded compact control but rejects unknown tools/)
assert.match(tests, /downstream abort cancels the Cursor stream and relay close does not hang/)
assert.match(tests, /ordinary tool examples remain text and do not trigger a correction request/)
assert.match(tests, /mixed tool JSON and fabricated result is corrected to structured tool_use without leaking raw text/)
assert.match(tests, /Grok Sand encodes native tool schemas and structured tool-result history/)
assert.match(tests, /Fable Sand encodes native tool schemas and structured tool-result history/)
assert.match(resumeTests, /Cursor Sand resume ids validate against CCB JSONL instead of Cursor workspace store/)
assert.match(tests, /interrupt before cold Sand preparation prevents submission/)
assert.match(tests, /shutdown during cold Sand preparation waits and prevents resurrection/)
assert.match(tests, /shutdown during Sand preheat waits and leaves no revived runner/)
assert.match(tests, /routing shutdown during deferred preparation prevents resurrection/)
assert.match(tests, /every concrete catalog Cursor model maps to its Sand InferenceService id/)
assert.match(tests, /credential selector parses a high-numbered Sand slot and records the same binding/)
assert.match(tests, /failed credential rebinds within the same transport but refuses a native-to-Sand failover/)
assert.match(tests, /concrete model quota-family changes reselect an eligible key before the next turn/)
assert.match(wrapper, /\/usr\/bin\/sort -n/)
assert.match(wrapperTests, /ten-key selection stays numeric and resolves billing to the tenth account/)
assert.match(wrapperTests, /an immutable generation keeps a bound Sand account stable after pool compaction/)
assert.match(tests, /pool generation changes rebind stable account identity before reading a reused slot/)
assert.match(materializer, /CURSOR_POOL_GENERATIONS_DIR/)
assert.match(materializer, /CURSOR_POOL_IDENTITIES_FILE/)
assert.match(wrapper, /printf 'v2 %s %s %s\\n'/)
assert.match(quota, /planStableCursorQuotaUpdate/)
assert.match(bridge, /stableAccountId: stableIdentityProvided \? cursorAccountId : undefined/)
assert.match(bridge, /stableIdentityProvided && !stableIdentityComplete/)
assert.match(frames, /CursorStablePoolIdentity/)
assert.match(commercialDeploy, /check-v5-cursor-sand-inference\.ts/)
assert.match(selfhostRelease, /check-v5-cursor-sand-inference\.ts/)

console.log('[cursor-sand-inference] PASS — Sand keys use InferenceService with native tool schemas; native Cursor stays isolated to native keys and Auto')
